import csv
import io
from datetime import UTC, date, datetime
from decimal import Decimal

from app.core.report_export.export_models import (
    ReportColumn,
    ReportExportData,
    ReportRow,
    ReportSummary,
)
from app.core.report_export.exporters.csv_exporter import CSVExporter

_GENERATED_AT = datetime(2026, 7, 30, 12, 0, tzinfo=UTC)


def _make_data(**overrides: object) -> ReportExportData:
    defaults: dict[str, object] = {
        "title": "Fish Sales Analytics",
        "columns": [
            ReportColumn(title="Fish", key="fish_name"),
            ReportColumn(title="Revenue", key="revenue"),
            ReportColumn(title="Last Sold", key="last_sold_date"),
        ],
        "rows": [
            ReportRow(
                data={
                    "fish_name": "Pomfret",
                    "revenue": Decimal("1000.00"),
                    "last_sold_date": date(2026, 7, 1),
                }
            ),
            ReportRow(
                data={"fish_name": "Surmai", "revenue": Decimal("500.50"), "last_sold_date": None}
            ),
        ],
        "summary": [ReportSummary(label="Total Revenue", value=Decimal("1500.50"))],
        "generated_at": _GENERATED_AT,
        "generated_by": "admin@fisherp.test",
        "tenant_name": "Konkan Traders",
    }
    defaults.update(overrides)
    return ReportExportData(**defaults)


class TestCSVExporter:
    def test_content_type_and_extension(self) -> None:
        exporter = CSVExporter()
        assert exporter.file_extension == "csv"
        assert "csv" in exporter.content_type

    def test_header_row_matches_column_titles(self) -> None:
        output = CSVExporter().run(_make_data())
        reader = csv.reader(io.StringIO(output.decode("utf-8")))
        header = next(reader)
        assert header == ["Fish", "Revenue", "Last Sold"]

    def test_data_rows_contain_raw_unformatted_values(self) -> None:
        output = CSVExporter().run(_make_data())
        reader = csv.reader(io.StringIO(output.decode("utf-8")))
        rows = list(reader)
        assert rows[1] == ["Pomfret", "1000.00", "2026-07-01"]
        assert rows[2] == ["Surmai", "500.50", ""]

    def test_output_excludes_title_subtitle_summary_and_footer(self) -> None:
        """CSV is raw data only - unlike PDF/Excel, none of the
        presentation fields ever appear in the output (TASKS.md Sprint
        11 Session 5 Phase B: "No formatting. Raw values only.")."""
        output = CSVExporter().run(_make_data(footer="Generated by FishERP")).decode("utf-8")
        assert "Fish Sales Analytics" not in output
        assert "Total Revenue" not in output
        assert "Generated by FishERP" not in output
        assert "admin@fisherp.test" not in output

    def test_zero_rows_produces_header_only(self) -> None:
        output = CSVExporter().run(_make_data(rows=[])).decode("utf-8")
        reader = csv.reader(io.StringIO(output))
        rows = list(reader)
        assert rows == [["Fish", "Revenue", "Last Sold"]]

    def test_output_is_utf8_decodable(self) -> None:
        data = _make_data(
            rows=[
                ReportRow(
                    data={
                        "fish_name": "Bombay Duck – Bombil",
                        "revenue": Decimal("1.00"),
                        "last_sold_date": None,
                    }
                )
            ]
        )
        output = CSVExporter().run(data)
        assert "Bombay Duck – Bombil" in output.decode("utf-8")
