from datetime import UTC, datetime

import pytest
from pydantic import ValidationError

from app.core.report_export.export_models import (
    ColumnAlignment,
    ColumnFormat,
    ReportColumn,
    ReportExportData,
    ReportFilterDisplay,
    ReportRow,
    ReportSummary,
    ReportType,
)

_NOW = datetime(2026, 7, 30, tzinfo=UTC)


def _make_data(**overrides: object) -> ReportExportData:
    defaults: dict[str, object] = {
        "title": "Sales Report",
        "columns": [ReportColumn(title="Invoice Number", key="invoice_number")],
        "rows": [ReportRow(data={"invoice_number": "INV-1"})],
        "summary": [ReportSummary(label="Total Sales", value="100.00")],
        "generated_at": _NOW,
        "generated_by": "admin@fisherp.test",
        "tenant_name": "Konkan Traders",
    }
    defaults.update(overrides)
    return ReportExportData(**defaults)


class TestReportColumn:
    def test_defaults(self) -> None:
        column = ReportColumn(title="Revenue", key="revenue")
        assert column.alignment == ColumnAlignment.LEFT
        assert column.format == ColumnFormat.TEXT

    def test_explicit_alignment_and_format(self) -> None:
        column = ReportColumn(
            title="Revenue",
            key="revenue",
            alignment=ColumnAlignment.RIGHT,
            format=ColumnFormat.CURRENCY,
        )
        assert column.alignment == ColumnAlignment.RIGHT
        assert column.format == ColumnFormat.CURRENCY


class TestReportRow:
    def test_holds_arbitrary_typed_values(self) -> None:
        row = ReportRow(data={"revenue": 123, "name": "Pomfret", "date": None})
        assert row.data == {"revenue": 123, "name": "Pomfret", "date": None}


class TestReportSummary:
    def test_label_and_value(self) -> None:
        summary = ReportSummary(label="Total Revenue", value="348250.00")
        assert summary.label == "Total Revenue"
        assert summary.value == "348250.00"


class TestReportFilterDisplay:
    def test_label_and_value(self) -> None:
        display = ReportFilterDisplay(label="Date Range", value="2026-07-01 to 2026-07-31")
        assert display.label == "Date Range"
        assert display.value == "2026-07-01 to 2026-07-31"


class TestReportType:
    def test_known_report_values(self) -> None:
        assert ReportType("customer_ledger") is ReportType.CUSTOMER_LEDGER
        assert ReportType("fish_sales") is ReportType.FISH_SALES

    def test_unknown_report_value_rejected(self) -> None:
        with pytest.raises(ValueError):
            ReportType("not_a_real_report")


class TestReportExportData:
    def test_valid_construction(self) -> None:
        data = _make_data()
        assert data.title == "Sales Report"
        assert data.subtitle is None
        assert data.filters == []
        assert data.footer is None
        assert len(data.rows) == 1
        assert len(data.summary) == 1

    def test_optional_fields_round_trip(self) -> None:
        data = _make_data(
            subtitle="Konkan Seafoods (CO-0001)",
            filters=[ReportFilterDisplay(label="Customer", value="Konkan Seafoods")],
            footer="Generated by FishERP",
        )
        assert data.subtitle == "Konkan Seafoods (CO-0001)"
        assert data.filters[0].label == "Customer"
        assert data.footer == "Generated by FishERP"

    def test_rejects_empty_columns(self) -> None:
        with pytest.raises(ValidationError, match="at least one column"):
            _make_data(columns=[])

    def test_rejects_duplicate_column_keys(self) -> None:
        with pytest.raises(ValidationError, match="unique"):
            _make_data(
                columns=[
                    ReportColumn(title="Invoice Number", key="invoice_number"),
                    ReportColumn(title="Invoice #", key="invoice_number"),
                ]
            )

    def test_rejects_row_missing_a_declared_column(self) -> None:
        with pytest.raises(ValidationError, match="missing values for columns"):
            _make_data(
                columns=[
                    ReportColumn(title="Invoice Number", key="invoice_number"),
                    ReportColumn(title="Customer", key="customer_name"),
                ],
                rows=[ReportRow(data={"invoice_number": "INV-1"})],
            )

    def test_allows_rows_with_extra_keys_beyond_declared_columns(self) -> None:
        data = _make_data(
            rows=[ReportRow(data={"invoice_number": "INV-1", "internal_id": "not-a-column"})]
        )
        assert data.rows[0].data["internal_id"] == "not-a-column"

    def test_allows_zero_rows(self) -> None:
        data = _make_data(rows=[])
        assert data.rows == []

    def test_allows_zero_summary_entries(self) -> None:
        data = _make_data(summary=[])
        assert data.summary == []

    def test_is_frozen(self) -> None:
        data = _make_data()
        with pytest.raises(ValidationError):
            data.title = "Something Else"  # type: ignore[misc]
