"use client";

import { Download } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

import { DataTableColumnHeader } from "@/components/data-table";
import type { DataTableColumn } from "@/components/data-table";
import { IconActionButton } from "@/components/layout/action-buttons";
import {
  getPartyHref,
  getSourceHref,
  PARTY_TYPE_PERMISSIONS,
  SOURCE_TYPE_PERMISSIONS,
} from "@/features/documents/constants/source-navigation";
import {
  DOCUMENT_PARTY_TYPE_LABELS,
  DOCUMENT_TYPE_LABELS,
} from "@/features/documents/constants/document-type";
import type { Document } from "@/features/documents/types/document";
import { formatDate } from "@/utils/format-date";
import { formatFileSize } from "@/utils/format-file-size";

/** A cell rendered as a real anchor (keyboard-focusable, has its own
 * accessible name from its text content) styled to match the design
 * system's own `Button` "link" variant tokens - reused directly rather
 * than the `Button` component itself, which would add unwanted
 * padding/height inside a compact table cell. `stopPropagation` is
 * defensive: this table has no `onRowClick` today, but a link cell
 * should never trigger a future row click if one is added later. */
function DocumentLinkCell({ href, children }: { href: string; children: ReactNode }) {
  return (
    <Link
      href={href}
      onClick={(event) => event.stopPropagation()}
      className="rounded-sm text-primary underline-offset-4 outline-none hover:underline focus-visible:ring-[3px] focus-visible:ring-ring/50"
    >
      {children}
    </Link>
  );
}

/**
 * The Document Center table's column set (Sprint 12 Session 8): Document
 * Type, Document Number, Party, Party Type, Generated By, Generated At,
 * File Type, File Size, Download. Only `document_number`/`generated_at`
 * are sortable, matching the backend's sortable field set
 * (app/modules/documents/schemas.py) exactly, since sorting is server-side.
 * There is no row-actions kebab here — `onDownload` renders as a single,
 * always-visible icon button (the only unconditional action a document row
 * has), not `createRowActionsColumn`'s dropdown, per this feature's
 * read-only, single-action scope.
 *
 * Document Number and Party become clickable links to their source/party
 * detail pages when the record actually carries that metadata (source_type/
 * source_id, or party_type/party_id) AND the caller holds the relevant
 * permission (`hasPermission`, from `usePermissions()`) - otherwise they
 * render as plain text, never a broken or unauthorized-looking link. A
 * record with no source metadata at all (every DocumentRecord from
 * Sessions 6/7, before source_type/source_id existed) always renders plain
 * text for Document Number - this is not an error state.
 */
export function getDocumentColumns(
  onDownload: (document: Document) => void,
  hasPermission: (code: string) => boolean
): DataTableColumn<Document>[] {
  return [
    {
      id: "document_type",
      accessorKey: "documentType",
      header: ({ column }) => <DataTableColumnHeader column={column} title="Document Type" />,
      enableSorting: false,
      cell: ({ row }) => DOCUMENT_TYPE_LABELS[row.original.documentType] ?? row.original.documentType,
    },
    {
      id: "document_number",
      accessorKey: "documentNumber",
      header: ({ column }) => <DataTableColumnHeader column={column} title="Document Number" />,
      cell: ({ row }) => {
        const { sourceType, sourceId, documentNumber } = row.original;
        const href = getSourceHref(sourceType, sourceId);
        const permission = sourceType ? SOURCE_TYPE_PERMISSIONS[sourceType] : null;
        if (href && permission && hasPermission(permission)) {
          return <DocumentLinkCell href={href}>{documentNumber}</DocumentLinkCell>;
        }
        return <span className="font-medium">{documentNumber}</span>;
      },
    },
    {
      id: "party",
      accessorKey: "partyName",
      header: ({ column }) => <DataTableColumnHeader column={column} title="Party" />,
      enableSorting: false,
      cell: ({ row }) => {
        const { partyType, partyId, partyName } = row.original;
        if (!partyName) return "—";
        const href = getPartyHref(partyType, partyId);
        const permission = partyType ? PARTY_TYPE_PERMISSIONS[partyType] : null;
        if (href && permission && hasPermission(permission)) {
          return <DocumentLinkCell href={href}>{partyName}</DocumentLinkCell>;
        }
        return partyName;
      },
    },
    {
      id: "party_type",
      accessorKey: "partyType",
      header: ({ column }) => <DataTableColumnHeader column={column} title="Party Type" />,
      enableSorting: false,
      cell: ({ row }) =>
        row.original.partyType ? DOCUMENT_PARTY_TYPE_LABELS[row.original.partyType] : "—",
    },
    {
      id: "generated_by_name",
      accessorKey: "generatedByName",
      header: ({ column }) => <DataTableColumnHeader column={column} title="Generated By" />,
      enableSorting: false,
      cell: ({ row }) => row.original.generatedByName,
    },
    {
      id: "generated_at",
      accessorKey: "generatedAt",
      header: ({ column }) => <DataTableColumnHeader column={column} title="Generated At" />,
      cell: ({ row }) => formatDate(row.original.generatedAt),
    },
    {
      id: "format",
      accessorKey: "fileExtension",
      header: ({ column }) => <DataTableColumnHeader column={column} title="File Type" />,
      enableSorting: false,
      cell: ({ row }) => row.original.fileExtension.toUpperCase(),
    },
    {
      id: "file_size",
      accessorKey: "fileSize",
      header: ({ column }) => <DataTableColumnHeader column={column} title="File Size" />,
      enableSorting: false,
      cell: ({ row }) => formatFileSize(row.original.fileSize),
      meta: { align: "right" },
    },
    {
      id: "actions",
      header: () => <span className="sr-only">Download</span>,
      enableSorting: false,
      enableHiding: false,
      enableResizing: false,
      size: 56,
      meta: { align: "right", hideFromToggle: true },
      cell: ({ row }) => (
        <IconActionButton
          icon={Download}
          label={`Download ${row.original.documentNumber}`}
          onClick={(event) => {
            event.stopPropagation();
            onDownload(row.original);
          }}
        />
      ),
    },
  ];
}
