"""boats table

Revision ID: 0066331bf93b
Revises: a100e0ef1d49
Create Date: 2026-07-21 17:08:41.322259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0066331bf93b'
down_revision: Union[str, Sequence[str], None] = 'a100e0ef1d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('boat_type', sa.String(length=50), nullable=True),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('engine_number', sa.String(length=50), nullable=True),
    sa.Column('engine_hp', sa.Integer(), nullable=True),
    sa.Column('captain_name', sa.String(length=255), nullable=True),
    sa.Column('captain_phone', sa.String(length=20), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boats_tenant', 'boats', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_boats_tenant_code', 'boats', ['tenant_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_boats_tenant_company', 'boats', ['tenant_id', 'company_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_boats_tenant_registration', 'boats', ['tenant_id', 'registration_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boats_tenant_registration', table_name='boats', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_boats_tenant_company', table_name='boats', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_boats_tenant_code', table_name='boats', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_boats_tenant', table_name='boats', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('boats')
    # ### end Alembic commands ###
