"""payments and payment_allocations tables

Revision ID: 37e193df7033
Revises: dbc5d32e12ce
Create Date: 2026-07-23 13:37:25.054971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e193df7033'
down_revision: Union[str, Sequence[str], None] = 'dbc5d32e12ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('unallocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_tenant', 'payments', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_payments_tenant_company', 'payments', ['tenant_id', 'company_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_payments_tenant_payment_date', 'payments', ['tenant_id', 'payment_date'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_payments_tenant_payment_number', 'payments', ['tenant_id', 'payment_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND payment_number IS NOT NULL'))
    op.create_index('ix_payments_tenant_status', 'payments', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_allocations_payment_invoice', 'payment_allocations', ['payment_id', 'invoice_id'], unique=True)
    op.create_index('ix_payment_allocations_tenant', 'payment_allocations', ['tenant_id'], unique=False)
    op.create_index('ix_payment_allocations_tenant_invoice', 'payment_allocations', ['tenant_id', 'invoice_id'], unique=False)
    op.create_index('ix_payment_allocations_tenant_payment', 'payment_allocations', ['tenant_id', 'payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_allocations_tenant_payment', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_tenant_invoice', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_tenant', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_payment_invoice', table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('ix_payments_tenant_status', table_name='payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_payments_tenant_payment_number', table_name='payments', postgresql_where=sa.text('deleted_at IS NULL AND payment_number IS NOT NULL'))
    op.drop_index('ix_payments_tenant_payment_date', table_name='payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_payments_tenant_company', table_name='payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_payments_tenant', table_name='payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('payments')
    # ### end Alembic commands ###
