"""trip_catches table

Revision ID: 3bfa1e6eab63
Revises: eaa8d78efe7a
Create Date: 2026-07-22 17:28:10.163075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfa1e6eab63'
down_revision: Union[str, Sequence[str], None] = 'eaa8d78efe7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_catches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('fish_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.Column('quantity_caught', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('sold_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('waste_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('landing_date', sa.Date(), nullable=False),
    sa.Column('landing_port', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_catches_tenant', 'trip_catches', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_trip_catches_tenant_fish', 'trip_catches', ['tenant_id', 'fish_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_trip_catches_tenant_trip', 'trip_catches', ['tenant_id', 'trip_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_catches_tenant_trip', table_name='trip_catches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_trip_catches_tenant_fish', table_name='trip_catches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_trip_catches_tenant', table_name='trip_catches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('trip_catches')
    # ### end Alembic commands ###
