"""unique company name index

Revision ID: 4ead5a8b4527
Revises: c40dad7f0957
Create Date: 2026-07-21 13:47:18.311251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ead5a8b4527'
down_revision: Union[str, Sequence[str], None] = 'c40dad7f0957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_companies_tenant_name', 'companies', ['tenant_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_tenant_name', table_name='companies', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
