"""supplier payments and supplier payment allocations tables

Revision ID: 59911f320635
Revises: ff9a6ef29763
Create Date: 2026-07-23 23:10:46.588894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59911f320635'
down_revision: Union[str, Sequence[str], None] = 'ff9a6ef29763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('unallocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_payments_tenant', 'supplier_payments', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_supplier_payments_tenant_payment_date', 'supplier_payments', ['tenant_id', 'payment_date'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_supplier_payments_tenant_payment_number', 'supplier_payments', ['tenant_id', 'payment_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND payment_number IS NOT NULL'))
    op.create_index('ix_supplier_payments_tenant_status', 'supplier_payments', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_supplier_payments_tenant_supplier', 'supplier_payments', ['tenant_id', 'supplier_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('supplier_payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_payment_id', sa.UUID(), nullable=False),
    sa.Column('purchase_bill_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bills.id'], ),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_payment_allocations_payment_bill', 'supplier_payment_allocations', ['supplier_payment_id', 'purchase_bill_id'], unique=True)
    op.create_index('ix_supplier_payment_allocations_tenant', 'supplier_payment_allocations', ['tenant_id'], unique=False)
    op.create_index('ix_supplier_payment_allocations_tenant_purchase_bill', 'supplier_payment_allocations', ['tenant_id', 'purchase_bill_id'], unique=False)
    op.create_index('ix_supplier_payment_allocations_tenant_supplier_payment', 'supplier_payment_allocations', ['tenant_id', 'supplier_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_payment_allocations_tenant_supplier_payment', table_name='supplier_payment_allocations')
    op.drop_index('ix_supplier_payment_allocations_tenant_purchase_bill', table_name='supplier_payment_allocations')
    op.drop_index('ix_supplier_payment_allocations_tenant', table_name='supplier_payment_allocations')
    op.drop_index('ix_supplier_payment_allocations_payment_bill', table_name='supplier_payment_allocations')
    op.drop_table('supplier_payment_allocations')
    op.drop_index('ix_supplier_payments_tenant_supplier', table_name='supplier_payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_supplier_payments_tenant_status', table_name='supplier_payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_supplier_payments_tenant_payment_number', table_name='supplier_payments', postgresql_where=sa.text('deleted_at IS NULL AND payment_number IS NOT NULL'))
    op.drop_index('ix_supplier_payments_tenant_payment_date', table_name='supplier_payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_supplier_payments_tenant', table_name='supplier_payments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
