"""purchase bill item line number counter

Revision ID: 61c9d619c8d3
Revises: 53818f638a33
Create Date: 2026-07-23 18:40:29.752565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c9d619c8d3'
down_revision: Union[str, Sequence[str], None] = '53818f638a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_bills', sa.Column('next_item_line_number', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_bills', 'next_item_line_number')
    # ### end Alembic commands ###
