"""auth and tenancy tables

Revision ID: 67c33121fc54
Revises: ccb7e18e8c13
Create Date: 2026-07-19 20:42:55.230287

"""
import datetime as dt
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from argon2 import PasswordHasher
from sqlalchemy.dialects import postgresql
from uuid6 import uuid7

# revision identifiers, used by Alembic.
revision: str = '67c33121fc54'
down_revision: Union[str, Sequence[str], None] = 'ccb7e18e8c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Seed data is inlined (not imported from app.modules.auth.constants) so this
# migration replays identically regardless of future changes to app code.
# Permission codes follow ARCHITECTURE.md §9.2's `resource:action` convention.
_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("company:view", "company", "view", "View company/customer records"),
    ("company:create", "company", "create", "Create company records"),
    ("company:edit", "company", "edit", "Edit company records"),
    ("company:delete", "company", "delete", "Delete company records"),
    ("company:view_credit", "company", "view_credit", "View company credit limit and balance"),
    ("fish:view", "fish", "view", "View fish master data"),
    ("fish:manage", "fish", "manage", "Create, edit and deactivate fish master data"),
    ("invoice:view", "invoice", "view", "View invoices"),
    ("invoice:create", "invoice", "create", "Create draft invoices"),
    ("invoice:edit", "invoice", "edit", "Edit draft invoices"),
    ("invoice:issue", "invoice", "issue", "Issue an invoice"),
    ("invoice:cancel", "invoice", "cancel", "Cancel an invoice or create a credit note"),
    ("payment:view", "payment", "view", "View payments"),
    ("payment:record", "payment", "record", "Record a payment and allocate it to invoices"),
    ("payment:delete", "payment", "delete", "Delete a payment"),
    ("payment:bounce", "payment", "bounce", "Mark a cheque payment as bounced"),
    ("boat:view", "boat", "view", "View boats"),
    ("trip:view", "trip", "view", "View trips"),
    ("trip:create", "trip", "create", "Create a trip"),
    ("trip:edit", "trip", "edit", "Edit a trip's expenses and catches"),
    ("trip:close", "trip", "close", "Close/settle a trip"),
    ("expense:view", "expense", "view", "View expenses"),
    ("expense:create", "expense", "create", "Record an expense"),
    ("expense:approve", "expense", "approve", "Approve an expense"),
    ("report:sales", "report", "sales", "View sales reports"),
    ("report:outstanding", "report", "outstanding", "View outstanding/aging reports"),
    ("report:profit", "report", "profit", "View business profit reports"),
    ("boat_report:profit", "boat_report", "profit", "View boat/trip profitability reports"),
    ("user:manage", "user", "manage", "Manage users and role assignments"),
    ("audit_log:view", "audit_log", "view", "View audit logs"),
    ("settings:manage", "settings", "manage", "Manage tenant settings"),
]

_ALL_CODES = [code for code, *_ in _PERMISSIONS]

_MANAGER_CODES = [
    code
    for code in _ALL_CODES
    if code
    not in {
        "company:delete",
        "company:view_credit",
        "payment:delete",
        "payment:bounce",
        "user:manage",
        "settings:manage",
    }
]

_ACCOUNTANT_CODES = [
    "company:view",
    "company:create",
    "fish:view",
    "invoice:view",
    "invoice:create",
    "invoice:edit",
    "invoice:issue",
    "invoice:cancel",
    "payment:view",
    "payment:record",
    "payment:delete",
    "payment:bounce",
    "boat:view",
    "trip:view",
    "expense:view",
    "expense:create",
    "report:sales",
    "report:outstanding",
    "report:profit",
    "boat_report:profit",
]

_OPERATOR_CODES = ["company:view", "fish:view", "invoice:view"]

# (role name, description, is_system, permission codes)
_ROLES: list[tuple[str, str, bool, list[str]]] = [
    ("super_admin", "Full system access across all modules", True, _ALL_CODES),
    ("admin", "Full tenant access across all modules", True, _ALL_CODES),
    ("manager", "Operational access excluding user/settings administration", True, _MANAGER_CODES),
    ("accountant", "Financial recording and reporting access", True, _ACCOUNTANT_CODES),
    ("operator", "Read-only access to core master data", True, _OPERATOR_CODES),
]

_DEFAULT_TENANT_SLUG = "default"
_SUPER_ADMIN_EMAIL = "admin@fisherp.local"
_SUPER_ADMIN_PASSWORD = "Admin@123"  # noqa: S105 - must be changed after first login


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fiscal_year_start_month BETWEEN 1 AND 12', name='ck_tenants_fiscal_month'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_tenant_email', 'users', ['tenant_id', sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_users_tenant_username', 'users', ['tenant_id', sa.literal_column('lower(username)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_entity', 'audit_logs', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###

    _seed_reference_data()


def _seed_reference_data() -> None:
    """Seed the default tenant, system roles, permission catalog and super admin."""
    bind = op.get_bind()

    tenants_table = sa.table(
        "tenants",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("status", sa.String),
        sa.column("settings", postgresql.JSONB),
        sa.column("fiscal_year_start_month", sa.Integer),
        sa.column("base_currency", sa.String),
    )
    roles_table = sa.table(
        "roles",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("tenant_id", postgresql.UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    permissions_table = sa.table(
        "permissions",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("code", sa.String),
        sa.column("resource", sa.String),
        sa.column("action", sa.String),
        sa.column("description", sa.String),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", postgresql.UUID(as_uuid=True)),
        sa.column("permission_id", postgresql.UUID(as_uuid=True)),
    )
    users_table = sa.table(
        "users",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("tenant_id", postgresql.UUID(as_uuid=True)),
        sa.column("email", sa.String),
        sa.column("username", sa.String),
        sa.column("password_hash", sa.String),
        sa.column("full_name", sa.String),
        sa.column("status", sa.String),
        sa.column("is_superuser", sa.Boolean),
        sa.column("failed_login_count", sa.Integer),
    )
    user_roles_table = sa.table(
        "user_roles",
        sa.column("user_id", postgresql.UUID(as_uuid=True)),
        sa.column("role_id", postgresql.UUID(as_uuid=True)),
        sa.column("assigned_at", sa.DateTime(timezone=True)),
    )

    now = dt.datetime.now(dt.timezone.utc)

    tenant_id = uuid7()
    bind.execute(
        tenants_table.insert().values(
            id=tenant_id,
            name="Default Organization",
            slug=_DEFAULT_TENANT_SLUG,
            status="active",
            settings={},
            fiscal_year_start_month=4,
            base_currency="INR",
        )
    )

    permission_ids = {code: uuid7() for code, *_ in _PERMISSIONS}
    bind.execute(
        permissions_table.insert(),
        [
            {
                "id": permission_ids[code],
                "code": code,
                "resource": resource,
                "action": action,
                "description": description,
            }
            for code, resource, action, description in _PERMISSIONS
        ],
    )

    role_ids = {name: uuid7() for name, *_ in _ROLES}
    bind.execute(
        roles_table.insert(),
        [
            {
                "id": role_ids[name],
                "tenant_id": tenant_id,
                "name": name,
                "description": description,
                "is_system": is_system,
            }
            for name, description, is_system, _codes in _ROLES
        ],
    )

    bind.execute(
        role_permissions_table.insert(),
        [
            {"role_id": role_ids[name], "permission_id": permission_ids[code]}
            for name, _description, _is_system, codes in _ROLES
            for code in codes
        ],
    )

    super_admin_id = uuid7()
    password_hash = PasswordHasher().hash(_SUPER_ADMIN_PASSWORD)
    bind.execute(
        users_table.insert().values(
            id=super_admin_id,
            tenant_id=tenant_id,
            email=_SUPER_ADMIN_EMAIL,
            username="admin",
            password_hash=password_hash,
            full_name="Super Admin",
            status="active",
            is_superuser=True,
            failed_login_count=0,
        )
    )

    bind.execute(
        user_roles_table.insert().values(
            user_id=super_admin_id,
            role_id=role_ids["super_admin"],
            assigned_at=now,
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_logs_tenant_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_tenant_username', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_users_tenant_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('tenants')
    op.drop_table('permissions')
    # ### end Alembic commands ###
