"""trips table

Revision ID: 72e2043a7f04
Revises: 72d5f6096c81
Create Date: 2026-07-21 18:27:20.721312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e2043a7f04'
down_revision: Union[str, Sequence[str], None] = '72d5f6096c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('boat_id', sa.UUID(), nullable=False),
    sa.Column('trip_number', sa.String(length=50), nullable=False),
    sa.Column('trip_type', sa.String(length=20), nullable=False),
    sa.Column('captain_name', sa.String(length=255), nullable=True),
    sa.Column('departure_port', sa.String(length=100), nullable=True),
    sa.Column('arrival_port', sa.String(length=100), nullable=True),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trips_tenant', 'trips', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_trips_tenant_boat', 'trips', ['tenant_id', 'boat_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_trips_tenant_trip_number', 'trips', ['tenant_id', 'trip_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trips_tenant_trip_number', table_name='trips', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_trips_tenant_boat', table_name='trips', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_trips_tenant', table_name='trips', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('trips')
    # ### end Alembic commands ###
