"""fish table

Revision ID: a100e0ef1d49
Revises: 4ead5a8b4527
Create Date: 2026-07-21 16:07:24.239223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a100e0ef1d49'
down_revision: Union[str, Sequence[str], None] = '4ead5a8b4527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('local_name', sa.String(length=255), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), server_default='kg', nullable=False),
    sa.Column('default_purchase_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('default_sale_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fish_tenant', 'fish', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_fish_tenant_code', 'fish', ['tenant_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_fish_tenant_name', 'fish', ['tenant_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fish_tenant_name', table_name='fish', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_fish_tenant_code', table_name='fish', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_fish_tenant', table_name='fish', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('fish')
    # ### end Alembic commands ###
