"""invoices and invoice items tables

Revision ID: b3f6a1d94c27
Revises: f27a4c6e9b13
Create Date: 2026-07-22 22:06:56.851146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f6a1d94c27'
down_revision: Union[str, Sequence[str], None] = 'f27a4c6e9b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('transport_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('other_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('round_off', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_tenant', 'invoices', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_invoices_tenant_company', 'invoices', ['tenant_id', 'company_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_invoices_tenant_invoice_date', 'invoices', ['tenant_id', 'invoice_date'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_invoices_tenant_invoice_number', 'invoices', ['tenant_id', 'invoice_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND invoice_number IS NOT NULL'))
    op.create_index('ix_invoices_tenant_status', 'invoices', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.UUID(), nullable=False),
    sa.Column('trip_catch_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trip_catch_id'], ['trip_catches.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_items_tenant', 'invoice_items', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_invoice_items_tenant_fish', 'invoice_items', ['tenant_id', 'fish_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_invoice_items_tenant_invoice', 'invoice_items', ['tenant_id', 'invoice_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_invoice_items_tenant_trip_catch', 'invoice_items', ['tenant_id', 'trip_catch_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_items_tenant_trip_catch', table_name='invoice_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoice_items_tenant_invoice', table_name='invoice_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoice_items_tenant_fish', table_name='invoice_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoice_items_tenant', table_name='invoice_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('invoice_items')
    op.drop_index('ix_invoices_tenant_status', table_name='invoices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoices_tenant_invoice_number', table_name='invoices', postgresql_where=sa.text('deleted_at IS NULL AND invoice_number IS NOT NULL'))
    op.drop_index('ix_invoices_tenant_invoice_date', table_name='invoices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoices_tenant_company', table_name='invoices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_invoices_tenant', table_name='invoices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('invoices')
    # ### end Alembic commands ###
