"""user avatar fields

Revision ID: e6bacbabbc01
Revises: 29830a833ff7
Create Date: 2026-08-22 15:18:16.400845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bacbabbc01'
down_revision: Union[str, Sequence[str], None] = '29830a833ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_storage_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_content_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_uploaded_at')
    op.drop_column('users', 'avatar_content_type')
    op.drop_column('users', 'avatar_storage_key')
    # ### end Alembic commands ###
