"""boat single active trip constraint

Revision ID: eaa8d78efe7a
Revises: 244f758929a6
Create Date: 2026-07-21 20:15:16.367300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa8d78efe7a'
down_revision: Union[str, Sequence[str], None] = '244f758929a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trips_boat_single_active', 'trips', ['boat_id'], unique=True, postgresql_where=sa.text("status IN ('departed', 'planned') AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trips_boat_single_active', table_name='trips', postgresql_where=sa.text("status IN ('departed', 'planned') AND deleted_at IS NULL"))
    # ### end Alembic commands ###
