"""purchase bill taxable amount

Revision ID: ff9a6ef29763
Revises: 61c9d619c8d3
Create Date: 2026-07-23 18:58:15.859596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9a6ef29763'
down_revision: Union[str, Sequence[str], None] = '61c9d619c8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_bills', sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_bills', 'taxable_amount')
    # ### end Alembic commands ###
